# Generated by Django 2.2.3 on 2019-07-24 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_medication'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionRefillRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateField(auto_now_add=True)),
                ('pharmacy_location', models.CharField(max_length=100)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.Medication')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
