# Generated by Django 2.2.3 on 2019-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20190724_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='preferred_pharmacy',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
